# Pandas methods

- 1. Introduction to pandas  
- 2. Top 5 or bottom 5 records  
- 3. renaming the column names  
- 4. statistical description  
- 5. adding new column  
- 6. dropping column  
- 7. Setting any column as index  
- 8. resetting index  
- 9. selecting row with index position  
- 10. selecting subsection of the dataset with LOC and iloc  
- 11. how to drop the row  
- 12. conditional filtering using "&" and "|"  
- 13. apply function on single column  
- 14. apply func on multiple column using lambda func  
- 15. sorting method  
- 16. min , max and their index position  
- 17. value_counts/unique/nunique/replace/map function  
- 18. treatment of duplicate values  
- 19. nlargest/nsmallest to get highest/lowest records  
- 20. sample of the dataset (by numbers or percentage)  
- 21. handling missing data  
- 22. isnull/notnull  
- 23. dropping missing values  
- 24. filling missing values  
- 25. group by operation on pandas  
- 26. combining dataframe-->concatenation  
- 27. combining dataframe-->merging-->join-->inner/left/right/outer  
- 28. text method on string data  
- 29. cleaning the uppercase/lowercase data

### 1. Introduction to pandas

**Pandas Library**
- It is useful for data processing and analysis.

**Pandas DataFrame**
- Pandas DataFrame is a two-dimensional tabular data structure with labelled axes (rows and columns).
- DataFrame is a table of columns and rows in pandas that we can easily restructure and filter.
- **Formal Definition:** A group of pandas Series objects that share the same index.

In [ ]:
import pandas as pd
import numpy as np

## Reading data

In [ ]:
iris_df = pd.read_excel('iris.xlsx')
iris_df.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df = pd.read_csv("tips.csv")
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [ ]:
url = "http://www.basketball-reference.com/leagues/NBA_2015_totals.html"
BB_data = pd.read_html(url)

In [ ]:
# Display the BB_data variable
BB_data

[        Rk             Player   Age Team  Pos     G    GS      MP     FG  \
 0      1.0       James Harden  25.0  HOU   SG  81.0  81.0  2981.0  647.0
 1      2.0      Stephen Curry  26.0  GSW   PG  80.0  80.0  2613.0  653.0
 2      3.0  Russell Westbrook  26.0  OKC   PG  67.0  67.0  2302.0  627.0
 3      4.0       LeBron James  30.0  CLE   SF  69.0  69.0  2493.0  624.0
 4      5.0     Damian Lillard  24.0  POR   PG  82.0  82.0  2925.0  590.0
 ..     ...                ...   ...  ...  ...   ...   ...     ...    ...
 647  489.0        Malcolm Lee  24.0  PHI   SG   1.0   0.0     2.0    0.0
 648  490.0        Kalin Lucas  25.0  MEM   PG   1.0   0.0     6.0    0.0
 649  491.0       Ronny Turiaf  32.0  MIN    C   2.0   0.0    19.0    0.0
 650  492.0         David Wear  24.0  SAC   PF   2.0   0.0     7.0    0.0
 651    NaN     League Average   NaN  NaN  NaN   NaN   NaN     NaN    NaN

         FGA  ...    DRB    TRB    AST    STL   BLK    TOV     PF     PTS  \
 0    1470.0  ...  384.0  459.0  565.0  154.0  60.0  321.0  208.0  2217.0
 1    1341.0  ...  285.0  341.0  619.0  163.0  16.0  249.0  158.0  1900.0
 2    1471.0  ...  364.0  488.0  574.0  140.0  14.0  293.0  184.0  1886.0
 3    1279.0  ...  365.0  416.0  511.0  109.0  49.0  272.0  135.0  1743.0
 4    1360.0  ...  329.0  378.0  507.0   97.0  21.0  222.0  164.0  1720.0
 ..      ...  ...    ...    ...    ...    ...   ...    ...    ...     ...
 647     1.0  ...    0.0    0.0    0.0    0.0   0.0    0.0    0.0     0.0
 648     1.0  ...    0.0    0.0    0.0    1.0   0.0    0.0    1.0     0.0
 649     0.0  ...    1.0    1.0    2.0    0.0   0.0    0.0    0.0     0.0
 650     2.0  ...    0.0    2.0    1.0    0.0   0.0    0.0    1.0     0.0
 651     NaN  ...    NaN    NaN    NaN    NaN   NaN    NaN    NaN     NaN

      Trp-Dbl                 Awards
 0        4.0          MVP-2,AS,NBA1
 1        0.0          MVP-1,AS,NBA1
 2       11.0          MVP-4,AS,NBA2
 3        2.0  MVP-3,DPOY-13,AS,NBA1
 4        0.0                     AS
 ..       ...                    ...
 647      0.0                    NaN
 648      0.0                    NaN
 649      0.0                    NaN
 650      0.0                    NaN
 651      NaN                    NaN

 [652 rows x 32 columns],
         Rk           Player   Age Team  Pos     G    GS     MP     FG    FGA  \
 0      1.0     LeBron James  30.0  CLE   SF  20.0  20.0  844.0  227.0  544.0
 1      2.0    Stephen Curry  26.0  GSW   PG  21.0  21.0  826.0  200.0  439.0
 2      3.0     James Harden  25.0  HOU   SG  17.0  17.0  636.0  129.0  294.0
 3      4.0    Klay Thompson  24.0  GSW   SG  21.0  21.0  761.0  149.0  334.0
 4      5.0    Blake Griffin  25.0  LAC   PF  14.0  14.0  557.0  140.0  274.0
 ..     ...              ...   ...  ...  ...   ...   ...    ...    ...    ...
 204  205.0       Greg Smith  24.0  DAL   PF   1.0   0.0    1.0    0.0    0.0
 205  206.0       Russ Smith  23.0  MEM   PG   2.0   0.0    3.0    0.0    0.0
 206  207.0  Mirza Teletović  29.0  BRK   PF   3.0   0.0   16.0    0.0    5.0
 207  208.0   Gerald Wallace  32.0  BOS   SF   1.0   0.0    4.0    0.0    1.0
 208    NaN   League Average   NaN  NaN  NaN   NaN   NaN    NaN    NaN    NaN

      ...    DRB    TRB    AST   STL   BLK   TOV    PF    PTS  Trp-Dbl  Awards
 0    ...  189.0  226.0  169.0  33.0  21.0  82.0  58.0  601.0      3.0     NaN
 1    ...   85.0  105.0  134.0  39.0   3.0  82.0  47.0  594.0      0.0     NaN
 2    ...   85.0   97.0  128.0  28.0   7.0  77.0  49.0  462.0      1.0     NaN
 3    ...   72.0   81.0   54.0  16.0  19.0  41.0  64.0  391.0      0.0     NaN
 4    ...  140.0  178.0   86.0  14.0  14.0  45.0  43.0  357.0      3.0     NaN
 ..   ...    ...    ...    ...   ...   ...   ...   ...    ...      ...     ...
 204  ...    0.0    0.0    0.0   0.0   0.0   0.0   0.0    0.0      0.0     NaN
 205  ...    0.0    0.0    2.0   0.0   0.0   0.0   0.0    0.0      0.0     NaN
 206  ...    4.0    4.0    0.0   1.0   0.0   1.0   1.0    0.0      0.0     NaN
 207  ...    1.0    1.0    0.0   0.0   0.0   0.0   0.0    0.0      0.0     NaN
 208  ...    NaN    NaN    NaN   NaN   NaN   NaN   NaN    NaN      NaN     NaN

 [209 rows x 32 columns]]

In [ ]:
first_bb_table = BB_data[0]
first_bb_table.head()

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards
0,1.0,James Harden,25.0,HOU,SG,81.0,81.0,2981.0,647.0,1470.0,...,384.0,459.0,565.0,154.0,60.0,321.0,208.0,2217.0,4.0,"MVP-2,AS,NBA1"
1,2.0,Stephen Curry,26.0,GSW,PG,80.0,80.0,2613.0,653.0,1341.0,...,285.0,341.0,619.0,163.0,16.0,249.0,158.0,1900.0,0.0,"MVP-1,AS,NBA1"
2,3.0,Russell Westbrook,26.0,OKC,PG,67.0,67.0,2302.0,627.0,1471.0,...,364.0,488.0,574.0,140.0,14.0,293.0,184.0,1886.0,11.0,"MVP-4,AS,NBA2"
3,4.0,LeBron James,30.0,CLE,SF,69.0,69.0,2493.0,624.0,1279.0,...,365.0,416.0,511.0,109.0,49.0,272.0,135.0,1743.0,2.0,"MVP-3,DPOY-13,AS,NBA1"
4,5.0,Damian Lillard,24.0,POR,PG,82.0,82.0,2925.0,590.0,1360.0,...,329.0,378.0,507.0,97.0,21.0,222.0,164.0,1720.0,0.0,AS

In [ ]:
df=pd.read_csv("tips.csv") # To import a csv file we use read_csv('filename')

In [ ]:
df.head() # this display the Top (Default = 5) Rows

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [ ]:
df.tail() # this display the Bottom (Default = 5) Rows

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
df.sample(5) # this display the random 5 rows

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
167,31.71,4.50,Male,No,Sun,Dinner,4,7.93,Michael Lawson,3566285921227119,Sun3719
210,30.06,2.00,Male,Yes,Sat,Dinner,3,10.02,Shawn Mendoza,30184049218122,Sat8361
220,12.16,2.20,Male,Yes,Fri,Lunch,2,6.08,Ricky Johnson,213109508670736,Fri4607
77,27.20,4.00,Male,No,Thur,Lunch,4,6.80,John Davis,30344778738589,Thur4924
173,31.85,3.18,Male,Yes,Sun,Dinner,2,15.92,Scott Perez,3577115550328507,Sun9335

# 3. To get the name of all the columns and how to rename the name of the columns

In [ ]:
df.columns # Outputs the name of all the Column in the dataset

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [ ]:
df.rename(columns={"Payer Name":"payer_name","CC Number":"cc_number"}) # To rename a column name we use a dictionary {'old name':'new name'}

#Using inplace=True applies the change directly to the DataFrame, so there's no need to assign the result to a new variable.

,total_bill,tip,sex,smoker,day,time,size,price_per_person,payer_name,cc_number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [ ]:
df.rename(columns={"Payer Name":"payer_name","CC Number":"cc_number"},inplace=True) # To rename a column name we use a dictionary {'old name':'new name'}
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,payer_name,cc_number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
df.shape

(244, 11)

In [ ]:
df1 = df.rename(columns=str.upper)
df1

,TOTAL_BILL,TIP,SEX,SMOKER,DAY,TIME,SIZE,PRICE_PER_PERSON,PAYER_NAME,CC_NUMBER,PAYMENT ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

# 4. Statistical description

In [ ]:
df.describe() # This function generates descriptive statistics

       total_bill         tip        size  price_per_person     cc_number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [ ]:
df['cc_number'] = df['cc_number'].astype(str)
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,payer_name,cc_number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
df.describe(include='object')

         sex smoker  day    time          payer_name Payment ID
count    244    244  244     244                 244        244
unique     2      2    4       2                 244        243
top     Male     No  Sat  Dinner  Christy Cunningham   Thur8084
freq     157    151   87     176                   1          2

In [ ]:
df.describe().transpose() # This swaps rows and columns, flipping the output for easier readability

,count,mean,std,min,25%,50%,75%,max
total_bill,244.0,1.978594e+01,8.902412e+00,3.070000e+00,1.334750e+01,1.779500e+01,2.412750e+01,5.081000e+01
tip,244.0,2.998279e+00,1.383638e+00,1.000000e+00,2.000000e+00,2.900000e+00,3.562500e+00,1.000000e+01
size,244.0,2.569672e+00,9.510998e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,6.000000e+00
price_per_person,244.0,7.888197e+00,2.914234e+00,2.880000e+00,5.800000e+00,7.255000e+00,9.390000e+00,2.027000e+01
cc_number,244.0,2.563496e+15,2.369340e+15,6.040679e+10,3.040731e+13,3.525318e+15,4.553675e+15,6.596454e+15

# To extract out single column or multiple column

In [ ]:
s1 = df["total_bill"].head(3) # Used to read a single column
s1

0    16.99
1    10.34
2    21.01
Name: total_bill, dtype: float64

In [ ]:
type(s1)

pandas.core.series.Series

In [ ]:
d1 = df[["total_bill"]].head(3) # Used to read a single column
d1

   total_bill
0       16.99
1       10.34
2       21.01

In [ ]:
type(d1)

pandas.core.frame.DataFrame

In [ ]:
df[["total_bill","tip"]].head(3) # for multiple columns name of the columns can be passed as a list

   total_bill   tip
0       16.99  1.01
1       10.34  1.66
2       21.01  3.50

# 5. Adding new column

In [ ]:
df["tip_percentage"]=round(df['tip']/df["total_bill"]*100,2) # Creates a new column 'tip_percentage' (or overwrites it if it already exists)

In [ ]:
df["tip_percentage"]

0       5.94
1      16.05
2      16.66
3      13.98
4      14.68
       ...
239    20.39
240     7.36
241     8.82
242     9.82
243    15.97
Name: tip_percentage, Length: 244, dtype: float64

In [ ]:
df["tip_percentage"]=round(df['tip']/df["total_bill"]*100,2).astype(str) + ' %'

In [ ]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,payer_name,cc_number,Payment ID,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.94 %
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.05 %
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.66 %
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.98 %
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.68 %

# 6. How to drop the column

In [ ]:
df.drop("tip_percentage",axis=1,inplace=True) # Drops the column and also make the changes to the dataset (inplace= true)

In [ ]:
# in case of deleting multiple column
# df.drop(['CC Number','tip_percentage'],axis=1)

In [ ]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,payer_name,cc_number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

# 7. How to set any column as index

In [ ]:
df=df.set_index("Payment ID").head()

In [ ]:
df.head(2)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,payer_name,cc_number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230

# 8. In order to reset index

In [ ]:
df=df.reset_index() # reset the index of a DataFrame back to the default integer index

In [ ]:
df.head(2)

,Payment ID,total_bill,tip,sex,smoker,day,time,size,price_per_person,payer_name,cc_number
0,Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
1,Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230

# 9. To select any specific rows with index postion

In [ ]:
df.iloc[0] # integer-based selection — meaning you select rows and/or columns by their position (not labels)

Payment ID                     Sun2959
total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
payer_name          Christy Cunningham
cc_number             3560325168603410
Name: 0, dtype: object

# 10. For selecting some subsection of the dataframe

In [ ]:
df.iloc[1:5]

,Payment ID,total_bill,tip,sex,smoker,day,time,size,price_per_person,payer_name,cc_number
1,Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
2,Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
3,Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
4,Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221

In [ ]:
# Selecting rows 4 to 9 (index 3 to 8) and columns 2 to 6 (index 1 to 5) using iloc
df.iloc[3:9, 1:6]

   total_bill   tip     sex smoker  day
3       23.68  3.31    Male     No  Sun
4       24.59  3.61  Female     No  Sun

In [ ]:
df=df.set_index("Payment ID") # Changes The default index

In [ ]:
df.head(2)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,payer_name,cc_number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230

In [ ]:
df.loc[["Sun2959","Sun4608"]]
#label-based indexing — you access rows and columns by their labels, not by position.

,total_bill,tip,sex,smoker,day,time,size,price_per_person,payer_name,cc_number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230

In [ ]:
df.head(2)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,payer_name,cc_number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230

# 11. How to drop the row

In [ ]:
df.drop("Sun2959",axis=0) # Deletes the row

,total_bill,tip,sex,smoker,day,time,size,price_per_person,payer_name,cc_number
Payment ID,,,,,,,,,,
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221

### 12. Conditional Filtering

- Typically in data analysis, our datasets are large enough that we don’t filter based on position but based on some condition.
- Conditional formatting allows us to select rows based on conditions on the column.
- This leads to discussion on organizing the data.

**Types of Conditional Filtering:**
- Condition filtering
- Filter by single condition
- Filter by multiple conditions
- Check against multiple values

In [ ]:
new_df=pd.read_csv("tips.csv")
new_df.head(2)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608

In [ ]:
#let filter out for the bill values greater than 40 dollars
new_df[new_df["total_bill"]>40]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
95,40.17,4.73,Male,Yes,Fri,Dinner,4,10.04,Aaron Bentley,180026611638690,Fri9628
102,44.30,2.50,Female,Yes,Sat,Dinner,3,14.77,Heather Cohen,379771118886604,Sat6240
142,41.19,5.00,Male,No,Thur,Lunch,5,8.24,Eric Andrews,4356531761046453,Thur3621
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,4112207559459910,Sun2337
184,40.55,3.00,Male,Yes,Sun,Dinner,2,20.27,Stephen Cox,3547798222044029,Sun5140
197,43.11,5.00,Female,Yes,Thur,Lunch,4,10.78,Brooke Soto,5544902205760175,Thur9313
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590

In [ ]:
# number of male customer
new_df[new_df["sex"]=="Male"].count() # Filters the male and then perform count

total_bill          157
tip                 157
sex                 157
smoker              157
day                 157
time                157
size                157
price_per_person    157
Payer Name          157
CC Number           157
Payment ID          157
dtype: int64

In [ ]:
# how to filter out with multiple condition
# and --> & ==> where both condition need to be true
# OR --> | ==> where either of condition must be true

In [ ]:
# show me the male who have paid the total bill more than 30
new_df[(new_df["total_bill"]>30) & (new_df["sex"]=="Male")].head(5) # AND condition both must be True

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239
39,31.27,5.00,Male,No,Sat,Dinner,3,10.42,Mr. Brandon Berry,6011525851069856,Sat6373
44,30.40,5.60,Male,No,Sun,Dinner,4,7.60,Todd Cooper,503846761263,Sun2274
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3552002592874186,Sun9677
56,38.01,3.00,Male,Yes,Sat,Dinner,4,9.50,James Christensen DDS,349793629453226,Sat8903

In [ ]:
new_df[(new_df["total_bill"]>30) | (new_df["sex"]=="Male")].tail(5) # OR condition either one must be True

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,Thomas Brown,4284722681265508,Sat2929
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,Sat9777
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17

In [ ]:
# another way of filtering is with isin function

In [ ]:
option=["Sat","Sun"]

In [ ]:
new_df[new_df["day"].isin(option)]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,Sat9777
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17

# 13. Use of apply function

In [ ]:
#what if i want to grab last four digit number of credit card number
#this can be acchieved by .apply function

In [ ]:
def Last_Four(num):
    return str(num)[-4:]

In [ ]:
Last_Four(945723487)

'3487'

In [ ]:
new_df["Last Four"]=new_df["CC Number"].apply(Last_Four) # Creating a new Column (Last Four) by extraction last 4 digit

In [ ]:
new_df.head(2)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,Last Four
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,3410
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,9230

In [ ]:
# based on price assing dollar sign== <10 -- "Less Price",10-30--"Medium Price",>30="High Price"

In [ ]:
def yelp(price):
    if price<10:
        return "Less Price"
    elif price >=10 and price <30:
        return "Medium Price"
    else:
        return "High Price"

In [ ]:
new_df["Yelp"]=new_df["total_bill"].apply(yelp)

In [ ]:
new_df.head(4)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,Last Four,Yelp
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,3410,Medium Price
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,9230,Medium Price
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,1322,Medium Price
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,5994,Medium Price

# 14. Apply function with multiple columns

In [ ]:
# problem statement is ==> based on the ratio total bill and tip categories customer whether he is generous or not

In [ ]:
def quality(total_bill,tip):
    if tip/total_bill > 0.10:  #if the the tip is more than 10% of the total bill we are returning Generous
        return "Generous"
    else:
        return "other"

In [ ]:
quality(16.00,2)

'Generous'

In [ ]:
new_df["Quality"] = new_df[["total_bill", "tip"]].apply(lambda x: quality(x[0], x[1]), axis=1)
new_df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,Last Four,Yelp,Quality
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,3410,Medium Price,other
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,9230,Medium Price,Generous
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,1322,Medium Price,Generous
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,5994,Medium Price,Generous
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,7221,Medium Price,Generous
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,2842,Medium Price,Generous
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,5404,Medium Price,other
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,7196,Medium Price,other
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,0950,Medium Price,other
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,8139,Medium Price,Generous

In [ ]:
# same result can be obtained by vectorize function

In [ ]:
new_df["Quality1"]=np.vectorize(quality)(new_df["total_bill"],new_df["tip"])
new_df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,Last Four,Yelp,Quality,Quality1
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,3410,Medium Price,other,other
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,9230,Medium Price,Generous,Generous
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,1322,Medium Price,Generous,Generous
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,5994,Medium Price,Generous,Generous
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,7221,Medium Price,Generous,Generous
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,2842,Medium Price,Generous,Generous
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,5404,Medium Price,other,other
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,7196,Medium Price,other,other
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,0950,Medium Price,other,other
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,8139,Medium Price,Generous,Generous

# 15. Sorting method in pandas

In [ ]:
df=pd.read_csv("tips.csv")

In [ ]:
df.head(2)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608

In [ ]:
# describe we already know we will directly see the sorting

In [ ]:
# let sort the values by tip value
df.sort_values("tip",ascending=False).head(5) # Sorting the values based on column tip

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025

In [ ]:
# we can do sorting with multiple column as well
df.sort_values(["tip","size"]).head()  #multi column sorting passing the columns in a list

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959

# 16. min max and there index position

In [ ]:
#what is max value of total bill
df["total_bill"].max() # returns the max value in the column

50.81

In [ ]:
df["total_bill"].idxmax() # returns the index postion of the max value in the column

170

- max amount of total bill is 50.81 and its index position is 170

In [ ]:
#what is min value of total bill
df["total_bill"].min() # returns the min value in the column

3.07

In [ ]:
#what is min value of total bill and what is its index position
df["total_bill"].idxmin() # returns the index postion of the min value in the column

67

In [ ]:
df.iloc[67]

total_bill                      3.07
tip                              1.0
sex                           Female
smoker                           Yes
day                              Sat
time                          Dinner
size                               1
price_per_person                3.07
Payer Name             Tiffany Brock
CC Number           4359488526995267
Payment ID                   Sat3455
Name: 67, dtype: object

In [ ]:
df.select_dtypes(include='number').corr()

#This selects only the numeric columns from the DataFrame and computes the pairwise correlation between them.
#Non-numeric columns (like strings or objects) are excluded because correlation only makes sense between numeric variables.

                  total_bill       tip      size  price_per_person  cc_number
total_bill          1.000000  0.675734  0.598315          0.647554   0.104576
tip                 0.675734  1.000000  0.489299          0.347405   0.110857
size                0.598315  0.489299  1.000000         -0.175359  -0.030239
price_per_person    0.647554  0.347405 -0.175359          1.000000   0.135240
cc_number           0.104576  0.110857 -0.030239          0.135240   1.000000

# 17. value counts/unique/nunique/replace/map func

In [ ]:
df["sex"].value_counts() # counts the values

sex
Male      157
Female     87
Name: count, dtype: int64

In [ ]:
df["day"].unique() #Gives a list of unique values in the column

array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

In [ ]:
df["day"].nunique() # Gives the count of the no of uniques in the column

4

In [ ]:
# how to use replace method==> replace female with "F" and Male with "M"
df.head(2)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608

In [ ]:
df["sex"].replace(["Female","Male"],["F","M"]) # Replaces the values

0      F
1      M
2      M
3      M
4      F
      ..
239    M
240    F
241    M
242    M
243    F
Name: sex, Length: 244, dtype: object

- Another way of doing the same thing is mapping

In [ ]:
mymap={"Female":"F","Male":"M"} #this is a dictionary

In [ ]:
df["sex"].map(mymap)
#This uses the dictionary mymap to transform or replace the values in the "sex" column.

0      F
1      M
2      M
3      M
4      F
      ..
239    M
240    F
241    M
242    M
243    F
Name: sex, Length: 244, dtype: object

# 18. How to treat duplicate values

In [ ]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Length: 244, dtype: bool

In [ ]:
df.drop_duplicates().head(5) # to drop the duplicates

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [ ]:
# use of between function
df[df["total_bill"].between(10, 30, inclusive="both")]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

# 19. nlargest and nsmallest

In [ ]:
#show me the 5 largest tip
df.nlargest(5,"tip")

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025

In [ ]:
# show me the 5 smallest tips
df.nsmallest(5,"tip")

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959

# 20. Random sample of the dataset by the number or percentage

In [ ]:
df.sample(5) # any five random rows will be selected

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
196,10.34,2.0,Male,Yes,Thur,Lunch,2,5.17,Eric Martin,30442491190342,Thur9862
178,9.60,4.0,Female,Yes,Sun,Dinner,2,4.80,Melanie Gray,4211808859168,Sun4598
197,43.11,5.0,Female,Yes,Thur,Lunch,4,10.78,Brooke Soto,5544902205760175,Thur9313
61,13.81,2.0,Male,Yes,Sat,Dinner,2,6.90,Ryan Hernandez,4766834726806,Sat3030
231,15.69,3.0,Male,Yes,Sat,Dinner,3,5.23,Jason Parks,4812333796161,Sat6334

In [ ]:
df.sample(frac=0.05) # 5% of the data will be selected ramdomly

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4577817359320969,Sun6686
25,17.81,2.34,Male,No,Sat,Dinner,4,4.45,Robert Perkins,30502930499388,Sat907
180,34.65,3.68,Male,Yes,Sun,Dinner,4,8.66,James Hebert DDS,676168737648,Sun7544
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801
139,13.16,2.75,Female,No,Thur,Lunch,2,6.58,Lindsey Meyer,676239597203,Thur6245
208,24.27,2.03,Male,Yes,Sat,Dinner,2,12.14,Jason Carter,4268942915626180,Sat6048
144,16.43,2.30,Female,No,Thur,Lunch,2,8.22,Linda Jones,6542729219645658,Thur9002
189,23.10,4.00,Male,Yes,Sun,Dinner,3,7.70,Richard Stevens,3560193117506187,Sun1821
109,14.31,4.00,Female,Yes,Sat,Dinner,2,7.16,Amanda Anderson,375638820334211,Sat2614
214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,4922302538691962,Sat3374
198,13.00,2.00,Female,Yes,Thur,Lunch,2,6.50,Katherine Bond,4926725945192,Thur437
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679

In [ ]:
# Average tip by gender
df.groupby('sex')['tip'].mean()

sex
Female    2.833448
Male      3.089618
Name: tip, dtype: float64

In [ ]:
# Tip stats by smoker
df.groupby('smoker')['tip'].describe()

        count      mean       std  min  25%   50%    75%   max
smoker
No      151.0  2.991854  1.377190  1.0  2.0  2.74  3.505   9.0
Yes      93.0  3.008710  1.401468  1.0  2.0  3.00  3.680  10.0

In [ ]:
# Multiple aggregations
df.groupby('day')[['total_bill', 'tip']].agg(['mean', 'max', 'min'])

     total_bill                    tip
           mean    max   min      mean    max   min
day
Fri   17.151579  40.17  5.75  2.734737   4.73  1.00
Sat   20.441379  50.81  3.07  2.993103  10.00  1.00
Sun   21.410000  48.17  7.25  3.255132   6.50  1.01
Thur  17.682742  43.11  7.51  2.771452   6.70  1.25

### 21. How to handle missing data

- Real world data will often be missing for a variety of reasons.
- Many machine learning models and statistical methods can't work with missing data; in such cases, we need to decide what to do with it.
- When reading missing values, pandas will display them as `NaN` values.

#### Option for missing data
- Keep it  
- Remove it  
- Replace it  

---

#### Keeping the missing data
- **Pros:** Does not manipulate or change the true data  
- **Cons:** Many methods or models do not support NaN values

---

#### Dropping or Removing the missing data
- **Pros:** Easy; can be based on rules  
- **Cons:** Chance of losing a lot of data or useful information can also be lost

---

#### Filling the missing data
- **Pros:** Potential to save a lot of data for use in training a model  
- **Cons:** Hardest to do and somewhat arbitrary -> potential to lead to false conclusions

In [ ]:
df=pd.read_csv("movie_scores.csv")

In [ ]:
df.head()

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

# 22. isnull and notnull

In [ ]:
df.isnull()
#Returns a DataFrame of the same shape as df, showing True for missing (null/NaN) values and False for non-missing values.

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0       False      False  False  False            False             False
1        True       True   True   True             True              True
2       False      False  False  False             True              True
3       False      False  False  False            False             False
4       False      False  False  False            False             False

In [ ]:
df.notnull()
#showing True where values are not missing and False where they are missing.

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0        True       True   True   True             True              True
1       False      False  False  False            False             False
2        True       True   True   True            False             False
3        True       True   True   True             True              True
4        True       True   True   True             True              True

In [ ]:
#show me the rows where all the pre movie score is given

In [ ]:
df[df["pre_movie_score"].notnull()]

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
#show me the rows where all the pre movie score is not given

In [ ]:
df[df["pre_movie_score"].isnull()]

  first_name last_name   age  sex  pre_movie_score  post_movie_score
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN

In [ ]:
#show me the rows where all the pre movie score is not given but first name is given

In [ ]:
df[(df["pre_movie_score"].isnull()) & (df["first_name"].notnull())]

  first_name last_name   age sex  pre_movie_score  post_movie_score
2       Hugh   Jackman  51.0   m              NaN               NaN

# 23.Dropping

In [ ]:
# this will remove the row which contain even one missing value and will not consider that row
df.dropna()

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
df.dropna(thresh=1)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

# 24. Filling Na values

In [ ]:
#help(df.fillna)

In [ ]:
df.fillna("xjd") #Fill/Replace any null value

  first_name last_name   age  sex pre_movie_score post_movie_score
0        Tom     Hanks  63.0    m             8.0             10.0
1        xjd       xjd   xjd  xjd             xjd              xjd
2       Hugh   Jackman  51.0    m             xjd              xjd
3      Oprah   Winfrey  66.0    f             6.0              8.0
4       Emma     Stone  31.0    f             7.0              9.0

In [ ]:
# fill with mean values
df["pre_movie_score"].fillna(df["pre_movie_score"].mean())

0    8.0
1    7.0
2    7.0
3    6.0
4    7.0
Name: pre_movie_score, dtype: float64

- there is one more method of filling the missing values it is interpolate when the category arrange in
linear order and there is missing values this function find interpolate value considering its linear order

### 25. Group By operation on Pandas

- A `groupby()` operation allows us to examine data per category basis.
- Group by is applicable on either categorical or discrete (when the column contains numerical values) columns.

In [ ]:
df=pd.read_csv("mpg.csv")
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

### How to suffix "Kg" in weight variable

In [ ]:
# Add "kg" to each value
df['weight_kg'] = df['weight'].astype(str) + ' kg'
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name,weight_kg
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu,3504 kg
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320,3693 kg
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite,3436 kg
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst,3433 kg
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino,3449 kg

### How to remove "kg" from weight variable

In [ ]:
df['weight_new'] = df['weight_kg'].str.replace(' kg', '').astype(int)
df.head(2)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name,weight_kg,weight_new
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu,3504 kg,3504
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320,3693 kg,3693

In [ ]:
df["model_year"].value_counts()

model_year
73    40
78    36
76    34
82    31
75    30
70    29
79    29
80    29
81    29
71    28
72    28
77    28
74    27
Name: count, dtype: int64

In [ ]:
df.groupby(["model_year"]).mean(numeric_only=True) # Seeing the mean of based on each model_year

,mpg,cylinders,displacement,horsepower,weight,acceleration
model_year,,,,,,
70,17.689655,6.758621,281.413793,147.827586,3372.793103,12.948276
71,21.250000,5.571429,209.750000,107.037037,2995.428571,15.142857
72,18.714286,5.821429,218.375000,120.178571,3237.714286,15.125000
73,17.100000,6.375000,256.875000,130.475000,3419.025000,14.312500
74,22.703704,5.259259,171.740741,94.230769,2877.925926,16.203704
75,20.266667,5.600000,205.533333,101.066667,3176.800000,16.050000
76,21.573529,5.647059,197.794118,101.117647,3078.735294,15.941176
77,23.375000,5.464286,191.392857,105.071429,2997.357143,15.435714
78,24.061111,5.361111,177.805556,99.694444,2861.805556,15.805556
79,25.093103,5.827586,206.689655,101.206897,3055.344828,15.813793
80,33.696552,4.137931,115.827586,77.481481,2436.655172,16.934483
81,30.334483,4.620690,135.310345,81.035714,2522.931034,16.306897
82,31.709677,4.193548,128.870968,81.466667,2453.548387,16.638710

In [ ]:
df.groupby(["model_year","cylinders"]).mean(numeric_only=True) # Seeing the mean of based on each model_year and cylinders

                            mpg  displacement  horsepower       weight  \
model_year cylinders
70         4          25.285714    107.000000   87.714286  2292.571429
           6          20.500000    199.000000   91.750000  2710.500000
           8          14.111111    367.555556  183.666667  3940.055556
71         4          27.461538    101.846154   77.583333  2056.384615
           6          18.000000    243.375000   98.875000  3171.875000
           8          13.428571    371.714286  166.857143  4537.714286
72         3          19.000000     70.000000   97.000000  2330.000000
           4          23.428571    111.535714   85.142857  2382.642857
           8          13.615385    344.846154  159.692308  4228.384615
73         3          18.000000     70.000000   90.000000  2124.000000
           4          22.727273    109.272727   82.909091  2338.090909
           6          19.000000    212.250000  102.125000  2917.125000
           8          13.200000    365.250000  170.000000  4279.050000
74         4          27.800000     96.533333   74.000000  2151.466667
           6          17.857143    230.428571  101.666667  3320.000000
           8          14.200000    315.200000  146.000000  4438.400000
75         4          25.250000    114.833333   84.916667  2489.250000
           6          17.583333    233.750000   96.750000  3398.333333
           8          15.666667    330.500000  142.000000  4108.833333
76         4          26.766667    106.333333   75.600000  2306.600000
           6          20.000000    221.400000   98.700000  3349.600000
           8          14.666667    324.000000  146.333333  4064.666667
77         3          21.500000     80.000000  110.000000  2720.000000
           4          29.107143    106.500000   78.785714  2205.071429
           6          19.500000    220.400000  102.000000  3383.000000
           8          16.000000    335.750000  152.375000  4177.500000
78         4          29.576471    112.117647   79.705882  2296.764706
           5          20.300000    131.000000  103.000000  2830.000000
           6          19.066667    213.250000  109.833333  3314.166667
           8          19.050000    300.833333  135.500000  3563.333333
79         4          31.525000    113.583333   75.750000  2357.583333
           5          25.400000    183.000000   77.000000  3530.000000
           6          22.950000    205.666667  105.000000  3025.833333
           8          18.630000    321.400000  131.900000  3862.900000
80         3          23.700000     70.000000  100.000000  2420.000000
           4          34.612000    111.000000   74.043478  2360.080000
           5          36.400000    121.000000   67.000000  2950.000000
           6          25.900000    196.500000  111.000000  3145.500000
81         4          32.814286    108.857143   72.950000  2275.476190
           6          23.428571    184.000000  100.714286  3093.571429
           8          26.600000    350.000000  105.000000  3725.000000
82         4          32.071429    118.571429   79.148148  2402.321429
           6          28.333333    225.000000  102.333333  2931.666667

                      acceleration
model_year cylinders
70         4             16.000000
           6             15.500000
           8             11.194444
71         4             16.961538
           6             14.750000
           8             12.214286
72         3             13.500000
           4             17.214286
           8             13.000000
73         3             13.500000
           4             17.136364
           6             15.687500
           8             12.250000
74         4             16.400000
           6             16.857143
           8             14.700000
75         4             15.833333
           6             17.708333
           8             13.166667
76         4             16.866667
           6             17.000000
           8             13.222222
77         3             13.500000
           4             16.064286
           6             16.900000
           8             13.662500
78         4             16.282353
           5             15.900000
           6             16.391667
           8             13.266667
79         4             15.991667
           5             20.100000
           6             15.433333
           8             15.400000
80         3             12.500000
           4             17.144000
           5             19.900000
           6             15.050000
81         4             16.466667
           6             15.442857
           8             19.000000
82         4             16.703571
           6             16.033333

In [ ]:
#describe functionwith groupby()
df.groupby("model_year").describe().transpose()

model_year                   70           71           72           73  \
mpg          count    29.000000    28.000000    28.000000    40.000000
             mean     17.689655    21.250000    18.714286    17.100000
             std       5.339231     6.591942     5.435529     4.700245
             min       9.000000    12.000000    11.000000    11.000000
             25%      14.000000    15.500000    13.750000    13.000000
             50%      16.000000    19.000000    18.500000    16.000000
             75%      22.000000    27.000000    23.000000    20.000000
             max      27.000000    35.000000    28.000000    29.000000
cylinders    count    29.000000    28.000000    28.000000    40.000000
             mean      6.758621     5.571429     5.821429     6.375000
             std       1.724926     1.665079     2.073708     1.807215
             min       4.000000     4.000000     3.000000     3.000000
             25%       6.000000     4.000000     4.000000     4.000000
             50%       8.000000     6.000000     4.000000     7.000000
             75%       8.000000     6.500000     8.000000     8.000000
             max       8.000000     8.000000     8.000000     8.000000
displacement count    29.000000    28.000000    28.000000    40.000000
             mean    281.413793   209.750000   218.375000   256.875000
             std     124.421380   115.102410   123.781964   121.722085
             min      97.000000    71.000000    70.000000    68.000000
             25%     198.000000    97.750000   109.250000   121.750000
             50%     307.000000   228.500000   131.000000   276.000000
             75%     383.000000   273.000000   326.000000   350.250000
             max     455.000000   400.000000   429.000000   455.000000
horsepower   count    29.000000    27.000000    28.000000    40.000000
             mean    147.827586   107.037037   120.178571   130.475000
             std      53.734844    38.566109    41.121368    46.412304
             min      46.000000    60.000000    54.000000    46.000000
             25%      95.000000    81.000000    86.750000    93.250000
             50%     150.000000    95.000000   104.500000   129.500000
             75%     198.000000   130.000000   150.750000   160.250000
             max     225.000000   180.000000   208.000000   230.000000
weight       count    29.000000    28.000000    28.000000    40.000000
             mean   3372.793103  2995.428571  3237.714286  3419.025000
             std     852.868663  1061.830859   974.520960   974.809133
             min    1835.000000  1613.000000  2100.000000  1867.000000
             25%    2648.000000  2110.750000  2285.500000  2554.500000
             50%    3449.000000  2798.000000  2956.000000  3338.500000
             75%    4312.000000  3603.250000  4169.750000  4247.250000
             max    4732.000000  5140.000000  4633.000000  4997.000000
acceleration count    29.000000    28.000000    28.000000    40.000000
             mean     12.948276    15.142857    15.125000    14.312500
             std       3.330982     2.666171     2.850032     2.754222
             min       8.000000    11.500000    11.000000     9.500000
             25%      10.000000    13.375000    13.375000    12.500000
             50%      12.500000    14.500000    14.500000    14.000000
             75%      15.000000    16.125000    16.625000    16.000000
             max      20.500000    20.500000    23.500000    21.000000

model_year                   74           75           76           77  \
mpg          count    27.000000    30.000000    34.000000    28.000000
             mean     22.703704    20.266667    21.573529    23.375000
             std       6.420010     4.940566     5.889297     6.675862
             min      13.000000    13.000000    13.000000    15.000000
             25%      16.000000    16.000000    16.750000    17.375000
             50%      24.000000    19.500000    21.000000    21.750000
             75%      27.000000    23.000000    26.375000    30.000000
             max      32.000000    33.000000    33.000000    36.000000
cylinders    count    27.000000    30.000000    34.000000    28.000000
             mean      5.259259     5.600000     5.647059     5.464286
             std       1.583390     1.522249     1.667558     1.815206
             min       4.000000     4.000000     4.000000     3.000000
             25%       4.000000     4.000000     4.000000     4.000000
             50%       4.000000     6.000000     6.000000     4.000000
             75%       6.000000     6.000000     7.500000     8.000000
             max       8.000000     8.000000     8.000000     8.000000
displacement count    27.000000    30.000000    34.000000    28.000000
             mean    171.740741   205.533333   197.794118   191.392857
             std      92.601127    87.669730    94.422256   107.813742
             min      71.000000    90.000000    85.000000    79.000000
             25%      90.000000   121.000000   102.500000    97.750000
             50%     122.000000   228.000000   184.000000   143.000000
             75%     250.000000   250.000000   291.000000   270.500000
             max     350.000000   400.000000   351.000000   400.000000
horsepower   count    26.000000    30.000000    34.000000    28.000000
             mean     94.230769   101.066667   101.117647   105.071429
             std      29.686775    26.577062    32.430592    36.095479
             min      52.000000    53.000000    52.000000    58.000000
             25%      75.000000    84.250000    78.250000    78.000000
             50%      88.000000    97.000000    93.500000    97.500000
             75%     103.750000   110.000000   120.000000   115.000000
             max     150.000000   170.000000   180.000000   190.000000
weight       count    27.000000    30.000000    34.000000    28.000000
             mean   2877.925926  3176.800000  3078.735294  2997.357143
             std     949.308571   765.179781   821.371481   912.825902
             min    1649.000000  1795.000000  1795.000000  1825.000000
             25%    2116.500000  2676.750000  2228.750000  2135.000000
             50%    2489.000000  3098.500000  3171.500000  2747.500000
             75%    3622.500000  3662.250000  3803.750000  3925.000000
             max    4699.000000  4668.000000  4380.000000  4335.000000
acceleration count    27.000000    30.000000    34.000000    28.000000
             mean     16.203704    16.050000    15.941176    15.435714
             std       1.688532     2.471737     2.801419     2.273391
             min      13.500000    11.500000    12.000000    11.100000
             25%      15.250000    14.125000    13.925000    14.000000
             50%      16.000000    16.000000    15.500000    15.650000
             75%      17.000000    17.375000    17.550000    16.925000
             max      21.000000    21.000000    22.200000    19.000000

model_year                   78           79           80           81  \
mpg          count    36.000000    29.000000    29.000000    29.000000
             mean     24.061111    25.093103    33.696552    30.334483
             std       6.898044     6.794217     7.037983     5.591465
             min      16.200000    15.500000    19.100000    17.600000
             25%      19.350000    19.200000    29.800000    26.600000
             50%      20.700000    23.900000    32.700000    31.600000
             75%      28.000000    31.800000    38.100000    34.400000
             max      43.100000    37.300000    46.600000    39.100000
cylinders    count    36.000000    29.000000    29.000000    29.000000
             mean      5.361111     5.827586     4.137931     4.620690
             std       1.495761     1.774199     0.580895     1.082781
             min       4.000000     4.000000     3.000000     4.000000
             25%       4.000000     4.000000     4.000000     4.000000
             50%       5.500000     6.000000     4.000000     4.000000
             75%       6.000000     8.000000     4.000000     6.000000
             max       8.000000     8.000000     6.000000     8.000000
displacement count    36.000000    29.000000    29.000000    29.000000
             mean    177.805556   206.689655   115.827586   135.310345
             std      76.012713    96.307581    33.744914    58.387929
             min      78.000000    85.000000    70.000000    79.000000
             25%     115.500000   121.000000    90.000000    98.000000
             50%     159.500000   183.000000   107.000000   119.000000
             75%     231.000000   302.000000   140.000000   151.000000
             max     318.000000   360.000000   225.000000   350.000000
horsepower   count    36.000000    29.000000    27.000000    28.000000
             mean     99.694444   101.206897    77.481481    81.035714
             std      28.436214    28.455955    18.173037    18.105620
             min      48.000000    65.000000    48.000000    58.000000
             25%      82.500000    77.000000    66.000000    65.000000
             50%      97.000000    90.000000    75.000000    75.500000
             75%     116.250000   125.000000    90.000000    89.000000
             max     165.000000   155.000000   132.000000   120.000000
weight       count    36.000000    29.000000    29.000000    29.000000
             mean   2861.805556  3055.344828  2436.655172  2522.931034
             std     626.023907   747.881497   432.235491   533.600501
             min    1800.000000  1915.000000  1835.000000  1755.000000
             25%    2282.500000  2556.000000  2110.000000  2065.000000
             50%    2910.000000  3190.000000  2335.000000  2385.000000
             75%    3410.000000  3725.000000  2800.000000  2900.000000
             max    4080.000000  4360.000000  3381.000000  3725.000000
acceleration count    36.000000    29.000000    29.000000    29.000000
             mean     15.805556    15.813793    16.934483    16.306897
             std       2.129915     2.952931     2.826694     2.192509
             min      11.200000    11.300000    11.400000    12.600000
             25%      14.475000    14.000000    15.100000    14.800000
             50%      15.750000    15.000000    16.500000    16.200000
             75%      16.825000    17.300000    18.700000    17.300000
             max      21.500000    24.800000    23.700000    20.700000

model_year                   82
mpg          count    31.000000
             mean     31.709677
             std       5.392548
             min      22.000000
             25%      27.000000
             50%      32.000000
             75%      36.000000
             max      44.000000
cylinders    count    31.000000
             mean      4.193548
             std       0.601074
             min       4.000000
             25%       4.000000
             50%       4.000000
             75%       4.000000
             max       6.000000
displacement count    31.000000
             mean    128.870968
             std      39.352037
             min      91.000000
             25%     105.000000
             50%     119.000000
             75%     142.000000
             max     262.000000
horsepower   count    30.000000
             mean     81.466667
             std      13.296962
             min      52.000000
             25%      70.000000
             50%      84.000000
             75%      88.000000
             max     112.000000
weight       count    31.000000
             mean   2453.548387
             std     354.276713
             min    1965.000000
             25%    2127.500000
             50%    2525.000000
             75%    2727.500000
             max    3035.000000
acceleration count    31.000000
             mean     16.638710
             std       2.484844
             min      11.600000
             25%      14.850000
             50%      16.400000
             75%      18.000000
             max      24.600000

# 26. Combining dataframe --> Concatenation
- Often the data you need exists in two separate sources. Fortunately, pandas makes it easy to combine these together.
- The simplest combination is if both sources are already in the same format—then concatenation through `pd.concat()` is all that's needed.

In [ ]:
data_one={"A":["A0","A1","A2","A3"],"B":["B0","B1","B2","B3"]}

In [ ]:
data_Two={"C":["C0","C1","C2","C3"],"D":["D0","D1","D2","D3"]}

In [ ]:
df1=pd.DataFrame(data_one)

In [ ]:
df2=pd.DataFrame(data_Two)

In [ ]:
df1

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [ ]:
df2

    C   D
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [ ]:
# concate them along column
pd.concat([df1,df2],axis=1)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [ ]:
# concate them along column
pd.concat([df1,df2],axis=0)

     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3   A3   B3  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1
2  NaN  NaN   C2   D2
3  NaN  NaN   C3   D3

In [ ]:
# we can know this not better approch to join the table

In [ ]:
# so to join the two table along the rows column name of both column must be matching

In [ ]:
df2.columns=df1.columns

In [ ]:
df2

    A   B
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [ ]:
df1

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [ ]:
pd.concat([df1,df2],axis=0)

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

### 27. Combining DataFrame --> Merging

- This is analogous to a JOIN in SQL.
- The `merge` method takes a key argument labeled `how`.
- There are three ways of merging: `how='inner'`, `how='outer'`, `how='left'`, or `how='right'`.

In [ ]:
registrations = pd.DataFrame({'reg_id':[1,2,3,4],'name':['Andrew','Virat','Claire','David']})
logins = pd.DataFrame({'log_id':[1,2,3,4],'name':['Xavier','Andrew','Yolanda','Virat']})

In [ ]:
registrations

   reg_id    name
0       1  Andrew
1       2   Virat
2       3  Claire
3       4   David

In [ ]:
logins

   log_id     name
0       1   Xavier
1       2   Andrew
2       3  Yolanda
3       4    Virat

In [ ]:
#lets first try with inner join

In [ ]:
pd.merge(registrations,logins,how="inner",on="name")

   reg_id    name  log_id
0       1  Andrew       2
1       2   Virat       4

- left and right Merge

In [ ]:
#left
pd.merge(registrations,logins,how="left",on="name")

   reg_id    name  log_id
0       1  Andrew     2.0
1       2   Virat     4.0
2       3  Claire     NaN
3       4   David     NaN

In [ ]:
#Right
pd.merge(registrations,logins,how="right",on="name")

   reg_id     name  log_id
0     NaN   Xavier       1
1     1.0   Andrew       2
2     NaN  Yolanda       3
3     2.0    Virat       4

In [ ]:
# outer merge
pd.merge(registrations,logins,how="outer",on="name")

   reg_id     name  log_id
0     1.0   Andrew     2.0
1     2.0    Virat     4.0
2     3.0   Claire     NaN
3     4.0    David     NaN
4     NaN   Xavier     1.0
5     NaN  Yolanda     3.0

# 28. Text method on string data

- Often text data needs to be cleaned or manipulated for processing.
- While we can always use a custom `apply()` function for these tasks, pandas comes with built-in string method calls.

In [ ]:
#split
email="milindgaur@gmail.com"
email.split("@") # Splits the values

['milindgaur', 'gmail.com']

In [ ]:
name="Milind"
name.isdigit()

False

In [ ]:
"7".isdigit()

True

In [ ]:
names=pd.Series(["Milind","Kanchan","Rohit",'Snehal'])

In [ ]:
names

0     Milind
1    Kanchan
2      Rohit
3     Snehal
dtype: object

In [ ]:
names.str.upper()

0     MILIND
1    KANCHAN
2      ROHIT
3     SNEHAL
dtype: object

In [ ]:
names.str.capitalize()

0     Milind
1    Kanchan
2      Rohit
3     Snehal
dtype: object

In [ ]:
names.str.lower()

0     milind
1    kanchan
2      rohit
3     snehal
dtype: object

# 29. How to clean the upper case/ lower case issues

In [ ]:
messy_names=pd.Series(["SaChin ","Kanchan","Rohit",'SNehal '])

In [ ]:
messy_names

0    SaChin
1    Kanchan
2      Rohit
3    SNehal
dtype: object

In [ ]:
messy_names.str.strip().str.capitalize()

#You use .str every time you want to apply a string method to a pandas Series of strings.
#You can’t chain .strip().capitalize() directly — those are Python string methods, not Series methods

0     Sachin
1    Kanchan
2      Rohit
3     Snehal
dtype: object