# Pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
print(pd.__version__)

2.0.3

In [3]:
print(np.__version__)

1.24.3

### Creating Pandas Series manually

In [3]:
data=np.random.randint(10,30,10)
data

array([18, 19, 13, 29, 23, 15, 11, 23, 25, 25])

In [4]:
type(data)

numpy.ndarray

In [5]:
# Creating Series
series=pd.Series(data)
series

0    18
1    19
2    13
3    29
4    23
5    15
6    11
7    23
8    25
9    25
dtype: int32

In [6]:
type(series)

pandas.core.series.Series

### Operations in Pandas Series

In [7]:
# To Search a value from Index 
series[4]

23

In [9]:
series>20

0    False
1    False
2    False
3     True
4     True
5    False
6    False
7     True
8     True
9     True
dtype: bool

In [8]:
# Search a value greater than 20
series[series>20]

3    29
4    23
7    23
8    25
9    25
dtype: int32

### Creating Pandas DataFrame manually

Creating Dataframe from Dictionary of Pandas Series

In [4]:
data1 = {"Name": ["Akash", "Hello", "World"],
        "Age": [25, 30,35],
        "City": ["Chd","Punjab","Delhi"]
}

In [5]:
data1

{'Name': ['Akash', 'Hello', 'World'],
 'Age': [25, 30, 35],
 'City': ['Chd', 'Punjab', 'Delhi']}

In [6]:
df1 = pd.DataFrame(data1)
df1

    Name  Age    City
0  Akash   25     Chd
1  Hello   30  Punjab
2  World   35   Delhi

In [8]:
import numpy as np
data={'a':pd.Series(np.random.randint(10,20,5)),
      'b':pd.Series(np.random.randint(5,8,5)),
      'c':pd.Series(5,index=[0,1,2])}
data

{'a': 0    19
 1    17
 2    18
 3    19
 4    15
 dtype: int32,
 'b': 0    6
 1    5
 2    5
 3    5
 4    5
 dtype: int32,
 'c': 0    5
 1    5
 2    5
 dtype: int64}

In [9]:
type(data)

dict

In [10]:
# Converting Dictionary of Pandas Series to DataFarme
df=pd.DataFrame(data)
df

    a  b    c
0  19  6  5.0
1  17  5  5.0
2  18  5  5.0
3  19  5  NaN
4  15  5  NaN

In [11]:
df.loc[2:3,'b']

2    5
3    5
Name: b, dtype: int32

### Basic Functionality / Operations on DataFrame

In [12]:
# Extracting a column from data frame
n=df['a'] #for single column only
n

0    19
1    17
2    18
3    19
4    15
Name: a, dtype: int32

In [13]:
n1=df[['a','b']]
n1

    a  b
0  19  6
1  17  5
2  18  5
3  19  5
4  15  5

In [14]:
type(n1)

pandas.core.frame.DataFrame

In [15]:
type(n)

pandas.core.series.Series

In [16]:
# Extracting 2 ormore columns from dataframe
p=df[['a','b','c']] #for multiple column - Imp
p

    a  b    c
0  19  6  5.0
1  17  5  5.0
2  18  5  5.0
3  19  5  NaN
4  15  5  NaN

In [17]:
type(p)

pandas.core.frame.DataFrame

In [18]:
df

    a  b    c
0  19  6  5.0
1  17  5  5.0
2  18  5  5.0
3  19  5  NaN
4  15  5  NaN

In [19]:
df.loc[2:,]

    a  b    c
2  18  5  5.0
3  19  5  NaN
4  15  5  NaN

In [20]:
# Extract an element from dataframe using Row Index
df.loc[2]

a    18.0
b     5.0
c     5.0
Name: 2, dtype: float64

In [21]:
# Extract an element from dataframe using Row Index and Column Index
df.loc[2,'b']

5

In [22]:
#Slicing multiple elements from dataframe using Row Index & Column Index. Here End Index is Included 
df.loc[2:3,'b':'c']

   b    c
2  5  5.0
3  5  NaN

In [23]:
# Slice multiple elements from dataframe
df.loc[2:,]

    a  b    c
2  18  5  5.0
3  19  5  NaN
4  15  5  NaN

In [24]:
df5 = pd.DataFrame(
[[4, 7, 10],
[5, 8, 11],
[6, 9, 12]],
index=[13, 14, 15],
columns=['a','b','c'])
df5

    a  b   c
13  4  7  10
14  5  8  11
15  6  9  12

### Find Missing Values in DataFrame

In [26]:
df

    a  b    c
0  19  6  5.0
1  17  5  5.0
2  18  5  5.0
3  19  5  NaN
4  15  5  NaN

In [27]:
df.isnull()

       a      b      c
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False   True
4  False  False   True

In [28]:
df.isnull().sum()

a    0
b    0
c    2
dtype: int64

In [29]:
# Drop columns with Missing Values
df.dropna(axis=1)

    a  b
0  19  6
1  17  5
2  18  5
3  19  5
4  15  5

In [30]:
# Drop rows with Missing Values
df.dropna(axis=0)

    a  b    c
0  19  6  5.0
1  17  5  5.0
2  18  5  5.0

In [31]:
# Fill NA values with 0 --> Fill happens on original df
df.fillna(0)

    a  b    c
0  19  6  5.0
1  17  5  5.0
2  18  5  5.0
3  19  5  0.0
4  15  5  0.0

In [32]:
# Filling NA by Forward Fill --> Fill happens on original df
df.fillna(method='ffill')

    a  b    c
0  19  6  5.0
1  17  5  5.0
2  18  5  5.0
3  19  5  5.0
4  15  5  5.0

In [33]:
# Fill na with backward --> Fill happens on original df
df.fillna(method='bfill')

    a  b    c
0  19  6  5.0
1  17  5  5.0
2  18  5  5.0
3  19  5  NaN
4  15  5  NaN

In [34]:
# Fill na with mean
df.fillna(df.mean())

    a  b    c
0  19  6  5.0
1  17  5  5.0
2  18  5  5.0
3  19  5  5.0
4  15  5  5.0

### Importing & Exporting Data

Reading Excel File

In [17]:
pwd

'C:\\Users\\hp\\Music\\Python Basics'

In [35]:
data=pd.read_excel('iris.xlsx')
data

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [36]:
data.head(5)

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [37]:
data.tail(10)

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

Exporting the DataFrame as a Excel file

In [38]:
data.to_excel('irisnew.xlsx')

### Reading file from different location

In [42]:
students_df=pd.read_excel("E:\\Data_Science\\Linear_Reg/Test_file.xlsx") 
students_df

    ID      Name   Subjects  Marks
0  103       Sam    English     81
1  105     Sandy    Physics     70
2  101    Andrew  Chemistry     66
3  106   Michael      Maths     91
4  106    Gautam      Maths     91
5  111  Michelle    English     88

In [43]:
titanic_df = pd.read_csv("titanic.csv")
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [44]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [46]:
titanic_df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [47]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [48]:
titanic_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [49]:
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [51]:
titanic_df["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [52]:
titanic_df.groupby('Sex').count()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Sex,,,,,,,,,,,
female,314,314,314,314,261,314,314,314,314,97,312
male,577,577,577,577,453,577,577,577,577,107,577

In [54]:
titanic_df.groupby(['Sex','Pclass']).mean(numeric_only=True)

               PassengerId  Survived        Age     SibSp     Parch  \
Sex    Pclass
female 1        469.212766  0.968085  34.611765  0.553191  0.457447
       2        443.105263  0.921053  28.722973  0.486842  0.605263
       3        399.729167  0.500000  21.750000  0.895833  0.798611
male   1        455.729508  0.368852  41.281386  0.311475  0.278689
       2        447.962963  0.157407  30.740707  0.342593  0.222222
       3        455.515850  0.135447  26.507589  0.498559  0.224784

                     Fare
Sex    Pclass
female 1       106.125798
       2        21.970121
       3        16.118810
male   1        67.226127
       2        19.741782
       3        12.661633