# Assignment 3 - Pandas

## Question 1	Import the attached Netflix csv file in Jupyter notebook and perform following operations using Pandas:
a)	Print the first 5 rows and last 5 rows of the dataframe
b)	Check how many rows and columns are there using Pandas function.
c)	Print all the column names.
d)	Calculate the descriptive statistics of all the variables(integer/float/object etc).
e)	Check the number of unique values for each column.
f)	Check the percentage of missing values for each column.
g)	Delete all the rows where Director column has missing values.
h)	Print all the records where country has Germany value (including West Germany). If any other country is there along with Germany, then that row should also come in output.
i)	Expand Duration column into 2 separate columns – First column having the numeric value and other having String. Eg: 3 seasons should be split in 2 columns having 3 in 1st column and seasons in 2nd column.
j)	Split Date added into 3 separate columns having date value in 1st column, month value in 2nd column and year value in 3rd.
k)	Print the number of TV shows/Movies released in each year.
l)	Rename the column title with movie_title.
m)	Split Listed_in column into 3 different columns with col name (Genre1, Genre2, Genre3). Split the column based on comma.

# Answer 1

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
netflix_df= pd.read_csv("C:\\Users\\richa\\netflix.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\richa\\netflix.csv'

In [ ]:
print("First 5 rows of the DataFrame:") #a)	Print the first 5 rows of the dataframe
netflix_df.head()

In [ ]:
print("Last 5 rows of the DataFrame:") #a)	Print the last 5 rows of the dataframe
netflix_df.tail()

In [ ]:
netflix_df.shape  #b)	Check how many rows and columns are there using Pandas function.

In [ ]:
netflix_df.columns #c)	Print all the column names

In [ ]:
netflix_df.describe(include='all') #d)	Calculate the descriptive statistics of all the variables(integer/float/object etc)

In [ ]:
print("Number of unique values for each column:") #e)	Check the number of unique values for each column
for col in netflix_df.columns:
    print(f"{col}: {netflix_df[col].nunique()} unique values")

In [ ]:
missing_percentage = (netflix_df.isnull().sum() / len(netflix_df)) * 100  #f)	Check the percentage of missing values for each column
missing_percentage.round(2)

In [ ]:
netflix_df.dropna(subset='director') #g)	Delete all the rows where Director column has missing values

In [ ]:
cntry_germany = netflix_df['country'].str.contains('Germany')   #h)	Print all the records where country has Germany value (including West Germany). If any other country is there along with Germany, then that row should also come in output.
cntry_west_germany = netflix_df['country'].str.contains('West Germany')
germany=netflix_df[cntry_germany | cntry_west_germany]
germany.head()

In [ ]:
germany=netflix_df[netflix_df['country'].str.contains('Germany', case=False, na=False)]

In [ ]:
netflix_df[['duration_value', 'duration_unit']] = netflix_df['duration'].str.split(' ',expand=True) #i)	Expand Duration column into 2 separate columns – First column having the numeric value and other having String. Eg: 3 seasons should be split in 2 columns having 3 in 1st column and seasons in 2nd column.
netflix_df.head()

In [ ]:
#j)	Split Date added into 3 separate columns having date value in 1st column, month value in 2nd column and year value in 3rd.     
netflix_df['date_added'] = pd.to_datetime(netflix_df['date_added'])
# Extract day, month, and year into new columns
netflix_df['day_added'] = netflix_df['date_added'].dt.day
netflix_df['month_added'] = netflix_df['date_added'].dt.month_name() 
netflix_df['year_added'] = netflix_df['date_added'].dt.year
netflix_df.head()

In [ ]:
netflix_df['release_year'].value_counts().sort_index()  # k)	Print the number of TV shows/Movies released in each year

In [ ]:
netflix_df.rename(columns={"title":"movie_title"},inplace=True)
netflix_df

In [ ]:
#m)	Split Listed_in column into 3 different columns with col name (Genre1, Genre2, Genre3). Split the column based on comma.
genre_columns = netflix_df['listed_in'].str.split(',', expand=True)
netflix_df['Genre1'] = genre_columns[0].str.strip()
netflix_df['Genre2'] = genre_columns[1].str.strip()
netflix_df['Genre3'] = genre_columns[2].str.strip()
netflix_df.head()

## Question 2 	Import both the attached files (student.csv and marks.csv) in Jupyter notebook and perform following operations:
a)	Combine both the dataframes into single dataframe which will have all the records from both the tables.
b)	Print the maximum and minimum marks Gender wise.
c)	Print all the students IDs and their marks who have scored more than the average marks of the class.
d)	Print the dataframe who are Males and are Employed.
e)	Create a new Column ‘IQ_level’ which will have 3 values (Intelligent, Mediocre, weak). If student scored than 80 then Tag him as Intelligent, if student scored between 50-80, then Mediocre, else weak.
f)	Count the number of males and females from each city.
g)	Print the top 5 Male scorers.
h)	Replace the Male value with M and Female value with F and export this dataframe to excel file in D: (D drive) and name the file as test.csv.
i)	Check if any student_ID is duplicated.
j)	Create a separate dataframe which will have all the Integer/Float variables.
k)	Get those Student_IDs which are present in Students table but not in Marks table.

## Answer 2

In [6]:
student_df= pd.read_csv("C:\\Users\\richa\\student.csv")

In [7]:
marks_df= pd.read_csv("C:\\Users\\richa\\marks.csv")

In [8]:
combined_df = pd.concat([student_df, marks_df],axis=0) #a) Combine both the dataframes into single dataframe which will have all the records from both the tables.
combined_df

     Student_id   Age  Gender      Grade Employed  Mark     City
0             1  19.0    Male  1st Class      yes   NaN      NaN
1             2  20.0  Female  2nd Class       no   NaN      NaN
2             3  18.0    Male  1st Class       no   NaN      NaN
3             4  21.0  Female  2nd Class       no   NaN      NaN
4             5  19.0    Male  1st Class       no   NaN      NaN
..          ...   ...     ...        ...      ...   ...      ...
224         228   NaN     NaN        NaN      NaN  99.0     Pune
225         229   NaN     NaN        NaN      NaN  70.0  Chennai
226         230   NaN     NaN        NaN      NaN  55.0    Delhi
227         231   NaN     NaN        NaN      NaN  97.0   Mumbai
228         232   NaN     NaN        NaN      NaN  59.0     Pune

[461 rows x 7 columns]

In [12]:
combined_df=pd.merge(student_df,marks_df,how="outer",on="Student_id")
combined_df

     Student_id  Age  Gender      Grade Employed  Mark     City
0             1   19    Male  1st Class      yes  95.0  Chennai
1             2   20  Female  2nd Class       no  70.0    Delhi
2             3   18    Male  1st Class       no  98.0   Mumbai
3             4   21  Female  2nd Class       no  75.0     Pune
4             5   19    Male  1st Class       no  89.0    Kochi
..          ...  ...     ...        ...      ...   ...      ...
227         228   21  Female  1st Class       no  99.0     Pune
228         229   20    Male  2nd Class       no  70.0  Chennai
229         230   20    Male  3rd Class      yes  55.0    Delhi
230         231   19  Female  1st Class      yes  97.0   Mumbai
231         232   20    Male  3rd Class      yes  59.0     Pune

[232 rows x 7 columns]

In [13]:
print("Maximum marks Gender-wise:")  #b)	Print the maximum marks Gender wise
combined_df.groupby('Gender')['Mark'].agg(['max'])

Maximum marks Gender-wise:

          max
Gender
Female   99.0
Male    100.0

In [14]:
print("Minimum marks Gender-wise:")  #b)	Print theminimum marks Gender wise
combined_df.groupby('Gender')['Mark'].agg(['min'])

Minimum marks Gender-wise:

         min
Gender
Female  40.0
Male    40.0

In [15]:
#c)	Print all the students IDs and their marks who have scored more than the average marks of the class.
average_marks = combined_df['Mark'].mean()
students_above_average = combined_df[combined_df['Mark'] > average_marks]
students_above_average[['Student_id','Mark']]

     Student_id  Mark
0             1  95.0
2             3  98.0
3             4  75.0
4             5  89.0
11           12  90.0
..          ...   ...
221         222  74.0
222         223  79.0
224         225  72.0
227         228  99.0
230         231  97.0

[137 rows x 2 columns]

In [16]:
males_employed_df = combined_df[(combined_df['Gender'] == 'Male') & (combined_df['Employed'] == 'yes')] #d)	Print the dataframe who are Males and are Employed.
males_employed_df

     Student_id  Age Gender      Grade Employed  Mark     City
0             1   19   Male  1st Class      yes  95.0  Chennai
5             6   20   Male  2nd Class      yes  69.0  Gwalior
7             8   21   Male  3rd Class      yes  54.0  Chennai
12           13   19   Male  1st Class      yes  92.0  Gwalior
14           15   19   Male  1st Class      yes  97.0     Pune
16           17   20   Male  2nd Class      yes  68.0  Gwalior
18           19   21   Male  2nd Class      yes  72.0  Chennai
29           30   19   Male  1st Class      yes  81.0  Chennai
34           35   20   Male  2nd Class      yes  79.0  Gwalior
36           37   21   Male  3rd Class      yes  53.0     Pune
41           42   19   Male  1st Class      yes  86.0    Delhi
43           44   19   Male  1st Class      yes  95.0     Pune
45           46   20   Male  2nd Class      yes  79.0    Delhi
47           48   21   Male  2nd Class      yes  67.0     Pune
58           59   19   Male  1st Class      yes  89.0     Pune
63           64   20   Male  2nd Class      yes  78.0    Delhi
65           66   21   Male  3rd Class      yes  59.0     Pune
70           71   19   Male  1st Class      yes  85.0    Kochi
72           73   19   Male  1st Class      yes  89.0   Bhopal
74           75   20   Male  2nd Class      yes  79.0    Delhi
76           77   21   Male  2nd Class      yes  77.0     Pune
87           88   19   Male  1st Class      yes  96.0     Pune
92           93   20   Male  2nd Class      yes  74.0    Kochi
94           95   21   Male  3rd Class      yes  50.0   Bhopal
99          100   19   Male  1st Class      yes  84.0    Kochi
101         102   19   Male  1st Class      yes  98.0  Chennai
103         104   20   Male  2nd Class      yes  78.0   Mumbai
105         106   21   Male  2nd Class      yes  77.0    Kochi
116         117   19   Male  1st Class      yes  90.0    Kochi
121         122   20   Male  2nd Class      yes  75.0   Mumbai
123         124   21   Male  3rd Class      yes  49.0  Chennai
128         129   19   Male  1st Class      yes  89.0  Gwalior
130         131   19   Male  1st Class      yes  90.0  Chennai
132         133   20   Male  2nd Class      yes  75.0   Mumbai
134         135   21   Male  2nd Class      yes  75.0    Kochi
145         146   19   Male  1st Class      yes  98.0   Mumbai
150         151   20   Male  2nd Class      yes  78.0     Pune
152         153   21   Male  3rd Class      yes  46.0  Gwalior
157         158   19   Male  1st Class      yes  92.0     Pune
159         160   19   Male  1st Class      yes  92.0    Delhi
161         162   20   Male  2nd Class      yes  79.0     Pune
163         164   21   Male  2nd Class      yes  75.0  Gwalior
174         175   19   Male  1st Class      yes  84.0     Pune
179         180   20   Male  2nd Class      yes  76.0    Delhi
181         182   21   Male  3rd Class      yes  58.0     Pune
186         187   19   Male  1st Class      yes  83.0    Kochi
188         189   19   Male  1st Class      yes  89.0   Bhopal
190         191   20   Male  2nd Class      yes  77.0    Delhi
192         193   21   Male  2nd Class      yes  75.0     Pune
203         204   19   Male  1st Class      yes  91.0     Pune
208         209   20   Male  2nd Class      yes  70.0   Mumbai
210         211   21   Male  3rd Class      yes  58.0    Kochi
215         216   19   Male  1st Class      yes  95.0   Mumbai
217         218   19   Male  1st Class      yes  96.0    Kochi
219         220   20   Male  2nd Class      yes  75.0   Bhopal
221         222   21   Male  2nd Class      yes  74.0    Kochi
229         230   20   Male  3rd Class      yes  55.0    Delhi
231         232   20   Male  3rd Class      yes  59.0     Pune

In [18]:
#e)	Create a new Column ‘IQ_level’ which will have 3 values (Intelligent, Mediocre, weak). If student scored than 80 then Tag him as Intelligent, if student scored between 50-80, then Mediocre, else weak
def score(Mark):
    if Mark>80:
        return "Intelligent"
    elif Mark >50 and Mark <80:
        return "Mediocre"
    else:
        return "weak"

In [19]:
combined_df["IQ_level"]=combined_df["Mark"].apply(score)
combined_df.sample(10)

     Student_id  Age  Gender      Grade Employed  Mark     City     IQ_level
28           29   20    Male  3rd Class       no  54.0   Bhopal     Mediocre
66           67   22  Female  3rd Class      yes  58.0  Chennai     Mediocre
148         149   21  Female  2nd Class       no  77.0  Gwalior     Mediocre
36           37   21    Male  3rd Class      yes  53.0     Pune     Mediocre
71           72   20  Female  3rd Class       no  54.0  Gwalior     Mediocre
109         110   21  Female  2nd Class      yes  76.0    Delhi     Mediocre
33           34   19    Male  1st Class       no  83.0    Kochi  Intelligent
45           46   20    Male  2nd Class      yes  79.0    Delhi     Mediocre
188         189   19    Male  1st Class      yes  89.0   Bhopal  Intelligent
20           21   20  Female  3rd Class      yes  49.0   Mumbai         weak

In [20]:
combined_df.groupby('City')['Gender'].value_counts()  #f)	Count the number of males and females from each city.

City     Gender
Bhopal   Male      15
         Female    13
Chennai  Male      18
         Female    15
Delhi    Male      20
         Female    12
Gwalior  Male      18
         Female    14
Kochi    Male      21
         Female    10
Mumbai   Female    16
         Male      16
Pune     Male      26
         Female    15
Name: count, dtype: int64

In [21]:
male_students=combined_df[combined_df['Gender'] == 'Male'] #g)	Print the top 5 Male scorers
top_5_male_scorers=male_students.sort_values(by='Mark',ascending=False).head(5)
top_5_male_scorers

     Student_id  Age Gender      Grade Employed   Mark     City     IQ_level
149         150   19   Male  1st Class       no  100.0   Bhopal  Intelligent
147         148   18   Male  1st Class       no   99.0    Kochi  Intelligent
62           63   19   Male  1st Class       no   98.0  Chennai  Intelligent
60           61   18   Male  1st Class       no   98.0  Gwalior  Intelligent
2             3   18   Male  1st Class       no   98.0   Mumbai  Intelligent

In [22]:
combined_df['Gender'].replace(["Female","Male"],["F","M"]) #h)	Replace the Male value with M and Female value with F and

0      M
1      F
2      M
3      F
4      M
      ..
227    F
228    M
229    M
230    F
231    M
Name: Gender, Length: 232, dtype: object

In [ ]:
combined_df.to_csv('test.csv') #export this dataframe to excel file in D: (D drive) and name the file as test.csv.

In [23]:
combined_df[combined_df.duplicated(subset=['Student_id'], keep=False)] #i)	Check if any student_ID is duplicated.

Empty DataFrame
Columns: [Student_id, Age, Gender, Grade, Employed, Mark, City, IQ_level]
Index: []

In [27]:
combined_df[combined_df.duplicated(subset=['Student_id'],keep=False)]

Empty DataFrame
Columns: [Student_id, Age, Gender, Grade, Employed, Mark, City, IQ_level]
Index: []

In [28]:
df_new = pd.DataFrame(      #j)	Create a separate dataframe which will have all the Integer/Float variables
[[4, 7.2, 10],
[5, 8, 11],
[6, 9.3, 12]],
index=[1, 2, 3],
columns=['a','b','c'])
df_new

   a    b   c
1  4  7.2  10
2  5  8.0  11
3  6  9.3  12

In [29]:
merged_for_missing_studentid = pd.merge(student_df, marks_df, on='Student_id', how='left') #k)	Get those Student_IDs which are present in Students table but not in Marks table.
merged_for_missing_studentid

     Student_id  Age  Gender      Grade Employed  Mark     City
0             1   19    Male  1st Class      yes  95.0  Chennai
1             2   20  Female  2nd Class       no  70.0    Delhi
2             3   18    Male  1st Class       no  98.0   Mumbai
3             4   21  Female  2nd Class       no  75.0     Pune
4             5   19    Male  1st Class       no  89.0    Kochi
..          ...  ...     ...        ...      ...   ...      ...
227         228   21  Female  1st Class       no  99.0     Pune
228         229   20    Male  2nd Class       no  70.0  Chennai
229         230   20    Male  3rd Class      yes  55.0    Delhi
230         231   19  Female  1st Class      yes  97.0   Mumbai
231         232   20    Male  3rd Class      yes  59.0     Pune

[232 rows x 7 columns]

## Question 3.	Explain the concept of missing values. How can you identify the missing values in a Pandas DataFrame ?
What are the different ways of treating/Imputing/Deleting the missing values.
Explain with example.

# Answer 3

## Real world data will often be missing for a variety of reasons.
#Many machine learning models and statistical methods can't work with missing data; in such cases, we need to decide what to do with it.
#When reading missing values, pandas will display them as NaN values.
#Option for missing data
Keep it
Remove it
Replace it

In [ ]:
#Finding Missing Values and different ways of treating/Imputing/Deleting the missing values in DataFrame
combined_df.isnull()

df.isnull().sum()

# Drop columns with Missing Values
combined_df.dropna(axis=1) 

# Drop rows with Missing Values
combined_df.dropna(axis=0)

# Fill NA values with 0 --> Fill happens on original df
combined_df.fillna(0)

# Filling NA by Forward Fill --> Fill happens on original df
combined_df.fillna(method='ffill')

# Fill na with backward --> Fill happens on original df
combined_df.fillna(method='bfill') 

THese are methods and functions used to treat missing values.

In [30]:
combined_df.isnull()

     Student_id    Age  Gender  Grade  Employed   Mark   City  IQ_level
0         False  False   False  False     False  False  False     False
1         False  False   False  False     False  False  False     False
2         False  False   False  False     False  False  False     False
3         False  False   False  False     False  False  False     False
4         False  False   False  False     False  False  False     False
..          ...    ...     ...    ...       ...    ...    ...       ...
227       False  False   False  False     False  False  False     False
228       False  False   False  False     False  False  False     False
229       False  False   False  False     False  False  False     False
230       False  False   False  False     False  False  False     False
231       False  False   False  False     False  False  False     False

[232 rows x 8 columns]

In [32]:
combined_df.isnull().sum()

Student_id    0
Age           0
Gender        0
Grade         0
Employed      0
Mark          3
City          3
IQ_level      0
dtype: int64